/* =============================================================
   Inject the homepage FAQ accordion from content/pages/home.yml's
   faq.items list into index.html, between the FAQ:START / FAQ:END
   markers.

   Unlike the other CMS-managed home.yml fields (handled generically
   by build-pages.js via data-cms="key" text swaps), the FAQ list has
   a variable number of entries - editors can add/remove questions in
   /admin - so it needs its own repeating-markup renderer instead of
   a fixed set of tagged elements.

   Run via `npm run build:faq` (also wired into `npm run build`, so
   every Vercel deploy stays in sync with the CMS).
   ============================================================= */
const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const ROOT = path.join(__dirname, "..");
const HOME_YML = path.join(ROOT, "content", "pages", "home.yml");
const INDEX_HTML = path.join(ROOT, "index.html");
const START_MARKER = "<!-- FAQ:START — generated by scripts/build-faq.js from content/pages/home.yml (faq.items), do not hand-edit -->";
const END_MARKER = "<!-- FAQ:END -->";

function escapeHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function item(q) {
  return `            <div class="faq__item">
              <button class="faq__q" type="button"><span data-lang-el>${escapeHtml(q.q_el)}</span><span data-lang-en>${escapeHtml(q.q_en)}</span><span class="faq__icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg></span></button>
              <div class="faq__a"><div class="faq__a-inner"><span data-lang-el>${escapeHtml(q.a_el)}</span><span data-lang-en>${escapeHtml(q.a_en)}</span></div></div>
            </div>`;
}

function build() {
  if (!fs.existsSync(HOME_YML)) {
    console.warn("[build-faq] content/pages/home.yml not found — skipping.");
    return;
  }
  const data = yaml.load(fs.readFileSync(HOME_YML, "utf8")) || {};
  const items = (data.faq && data.faq.items) || [];
  if (!items.length) {
    console.warn("[build-faq] No entries found in faq.items — skipping.");
    return;
  }

  const html = fs.readFileSync(INDEX_HTML, "utf8");
  const startIdx = html.indexOf(START_MARKER);
  const endIdx = html.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    console.warn("[build-faq] FAQ markers not found in index.html — skipping.");
    return;
  }

  const block = `${START_MARKER}\n${items.map(item).join("\n")}\n            ${END_MARKER}`;
  const newHtml = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);
  fs.writeFileSync(INDEX_HTML, newHtml, "utf8");
  console.log(`[build-faq] Injected ${items.length} FAQ item(s) into index.html`);
}

build();
